---
- name: Pull docker image
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

#     - name: Remove Docker Container Files
#       shell: docker rm digicamp_backend:latest
        
    - name: Pull devops image
      docker_image:
        name: jpray/digicamp_backend:latest
        source: pull
        
    - name: copy docker file
      copy:
        src: docker-compose.yml
        dest: docker-compose.yml
    - name: list files
      shell:
        cmd: ls
    - name: dockercompose
      docker_compose:
        project_src: .
        state: present

...
