version: "3.7"
services:
  clientnode:
    image: jpray/digicamp_frontend:latest
    ports:
      - "8090:4200"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.5
  servernode:
    image: jpray/digicamp_backend:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    ports:
      - "9090:9090"
    depends_on:
      - "dbnode"
    environment:
      MYSQL_HOST: "dbnode"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Jay@1998"
      MYSQL_PORT: "3306"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.6
  dbnode:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/jayprakashray/Documents/projects/DockerCompose/dbnode:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Jay@1998"
      MYSQL_DATABASE: "digicampdb"
      MYSQL_PASSWORD: "Jay@1998"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.7

networks:
  net_ubuntu:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24



