version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
#     env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=Jay@1998
      - MYSQL_DATABASE=digicampdb
    ports:
      - "3307:3306"
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      
  frontend:
    image: jpray/digicamp_frontend:latest
    depends_on:
      - app
    ports:
      - 3000:3000
    container_name: digicamp_frontend
    command: npm start
    
  app:
    image: jpray/digicamp_backend:latest
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
#     env_file: ./.env
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/digicampdb?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "Jay@1998",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
